spring.application.name=AdToolBackend
server.port=8081

app.api-key=
app.url=https://api.openai.com/v1/chat/completions
app.model=gpt-4o-mini
app.temperature=0.0
app.max_tokens=400
app.top_p=1.0
app.frequency_penalty=0.0
app.presence_penalty=0.0


