POST http://localhost:8081/api/profile/register
Content-Type: application/json

{
  "name": "Alice",
  "passwordHash": "alicepass123"
}

###

POST http://localhost:8081/api/profile/login
Content-Type: application/json

{
    "name": "Alice",
    "passwordHash": "alicepass123"
}