/*
as an Entity class, it is mapped to the database. The Model part of the MVC structure
represents a user profile in the system
assigns a unique autogenerated id to each profile
stores profile information: name and hashed password
*/

package dk.ek.adtoolbackend.profile;

import jakarta.persistence.*;

@Entity

public class Profile {

    // fields + annotations
@Id
@GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;


@Column(unique = true)
    private String name;


    private String passwordHash;


    // constructors

    public Profile() {

    }

    // getters + setters
    public int getId() {
        return id;
    }

public void setId(int id) {
        this.id = id;
}

public String getName() {
    return name;
}

public void setName(String name) {
        this.name = name;
}

public String getPasswordHash() {
        return passwordHash;
}

public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
}


}
